# Setup PostgreSQL databases
---

- block:
    - name: Setup PostgreSQL databases
      community.postgresql.postgresql_db:
        name: '{{ item.value.name }}'
        encoding: "{{ item.value.encoding|default('unicode') }}"
        template: "{{ item.value.template|default('template1') }}"
        login_host: '{{ item.value.host|default(omit) }}'
        login_user: '{{ item.value.login_user|default(omit) }}'
        login_password: '{{ item.value.login_password|default(omit) }}'
        port: '{{ item.value.port|default(omit) }}'
        state: present
      loop_control:
        label: '{{ item.value.name }}'
      when: not 'template' in item.value.name
      with_dict: '{{ postgresql_databases }}'

    - name: Setup PostgreSQL users
      community.postgresql.postgresql_user:
        name: '{{ item.1.name }}'
        db: '{{ item.0.value.name }}'
        encrypted: '{{ item.1.password_encrypted|default(omit) }}'
        password: '{{ item.1.password }}'
        login_host: '{{ item.0.value.host|default(omit) }}'
        login_user: '{{ item.0.value.login_user|default(omit) }}'
        login_password: '{{ item.0.value.login_password|default(omit) }}'
        no_password_changes: '{{ not item.1.password_update|default(true) }}'
        port: '{{ item.0.value.port|default(omit) }}'
        priv: "{{ item.1.priv|default([])|join('/') or omit }}"
        role_attr_flags: "{{ item.1.role_flags|default([])|join(',') }}"
        state: present
      loop: "{{ postgresql_databases|dict2items|subelements('value.users', skip_missing=true) }}"
      loop_control:
        label: 'db->{{ item.0.value.name }} user->{{ item.1.name }}'
      when: not 'template' in item.0.value.name

    - name: Enable extensions to the PostgreSQL databases
      community.postgresql.postgresql_ext:
        name: '{{ item.1 }}'
        db: '{{ item.0.name }}'
        login_host: '{{ item.0.host|default(omit) }}'
        login_user: '{{ item.0.login_user|default(omit) }}'
        login_password: '{{ item.0.login_password|default(omit) }}'
        port: '{{ item.0.port|default(omit) }}'
        state: present
      loop: "{{ postgresql_databases.values()|selectattr('extensions', 'defined')|list|subelements('extensions') }}"
      loop_control:
        label: '{{ item.0.name }} extension {{ item.1 }}'

    - name: Allow PostgreSQL users to access PostgreSQL databases
      community.postgresql.postgresql_privs:
        db: '{{ item.0.value.name }}'
        login_host: '{{ item.0.value.host|default(omit) }}'
        login_user: '{{ item.0.value.login_user|default(omit) }}'
        login_password: '{{ item.0.value.login_password|default(omit) }}'
        port: '{{ item.0.value.port|default(omit) }}'
        priv: ALL
        role: '{{ item.1.name }}'
        state: present
        type: database
      loop: "{{ postgresql_databases|dict2items|subelements('value.users', skip_missing=true) }}"
      loop_control:
        label: 'db->{{ item.0.value.name }} user->{{ item.1.name }}'
      when: not 'template' in item.0.value.name

    - name: Allow PostgreSQL users to administrate PostgreSQL databases schema
      community.postgresql.postgresql_privs:
        db: '{{ item.0.value.name }}'
        login_host: '{{ item.0.value.host|default(omit) }}'
        login_user: '{{ item.0.value.login_user|default(omit) }}'
        login_password: '{{ item.0.value.login_password|default(omit) }}'
        port: '{{ item.0.value.port|default(omit) }}'
        objs: public
        priv: ALL
        role: '{{ item.1.name }}'
        state: present
        type: schema
      loop: "{{ postgresql_databases|dict2items|subelements('value.users', skip_missing=true) }}"
      loop_control:
        label: 'db->{{ item.0.value.name }} user->{{ item.1.name }}'
      when: not 'template' in item.0.value.name and item.1.schema_admin|default(false)|bool
  run_once: true
